### ISSUE TITLE
Ignoring <slot>

### ISSUE THREAD

**Issue by natedunn** [Etheryte/vue-raw-pre#1]
Nice job with this.

It would be nice to use slots, but obviously it gets escaped. Any ideas to make something like this work?

```vue
<v-raw-pre>
    <slot></slot>
</v-raw-pre>
```

Could it technically work to add a prop to ignore slots?

```vue
<v-raw-pre slot="true">
    <slot></slot>
</v-raw-pre>
```

**Comment by Etheryte** [comment]
Thanks for your kind words. Sadly, dynamic content is conceptually not possible with this [technical solution](https://github.com/Etheryte/vue-raw-pre#technical-details). Behind the scenes, vue-raw-pre works as a Webpack loader, handling the content at build time. By the time your application runs in the browser, all information about template contents elsewhere is already bundled away by other loaders and thus not available.

**Comment by natedunn** [comment]
Thank you for your quick response. This makes sense.
